-- MySQL Script generated by MySQL Workbench
-- Sun Dec 26 15:09:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema building_managment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema building_managment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `building_managment` DEFAULT CHARACTER SET utf8 ;
USE `building_managment` ;

-- -----------------------------------------------------
-- Table `building_managment`.`apartment_building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`apartment_building` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`apartment_building` (
  `appartment_building_id` INT NOT NULL AUTO_INCREMENT,
  `appartments` INT NULL,
  `location` VARCHAR(250) NULL,
  `apartment_buildingcol` VARCHAR(45) NULL,
  `admin_email` VARCHAR(200) NULL,
  PRIMARY KEY (`appartment_building_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`user` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`user` (
  `username` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `isAppartmentBuildingAdmin` BINARY(1) NOT NULL DEFAULT 0,
  `appartmentBuilding` INT NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `USER_APPARTMENT_BUILDING_FOREIGN_KEY`
    FOREIGN KEY (`appartmentBuilding`)
    REFERENCES `building_managment`.`apartment_building` (`appartment_building_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`announcements` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`announcements` (
  `announcement_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `body` TEXT(10000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  `user_email` VARCHAR(200) NOT NULL,
  `appartment_building` INT NOT NULL,
  PRIMARY KEY (`announcement_id`),
  CONSTRAINT `USER_BUILDING_MANAGMENT_FOREIGN_KEY`
    FOREIGN KEY (`user_email`)
    REFERENCES `building_managment`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `APPARTMENT_BUILDING_ANNOUNCEMENTS_FOREIGN_KEY`
    FOREIGN KEY (`appartment_building`)
    REFERENCES `building_managment`.`apartment_building` (`appartment_building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`expenses` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`expenses` (
  `expense_id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `month` VARCHAR(200) NOT NULL,
  `is_owner_expense` BIT NOT NULL,
  `appartment_building` INT NOT NULL,
  PRIMARY KEY (`expense_id`),
  CONSTRAINT `APPARTMENT_BUILDING_FOREIGN_KEY`
    FOREIGN KEY (`appartment_building`)
    REFERENCES `building_managment`.`apartment_building` (`appartment_building_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`dept` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`dept` (
  `dept_id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `user` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`dept_id`),
  CONSTRAINT `USER_DEPT_FOREIGN_KEY`
    FOREIGN KEY (`user`)
    REFERENCES `building_managment`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`appartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`appartment` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`appartment` (
  `appartment_id` INT NOT NULL AUTO_INCREMENT,
  `appartment_building` INT NOT NULL,
  PRIMARY KEY (`appartment_id`),
  CONSTRAINT `APPARMENT_BUILDING_KEY`
    FOREIGN KEY (`appartment_building`)
    REFERENCES `building_managment`.`apartment_building` (`appartment_building_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `building_managment`.`user_appartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `building_managment`.`user_appartment` ;

CREATE TABLE IF NOT EXISTS `building_managment`.`user_appartment` (
  `user_email` VARCHAR(200) NOT NULL,
  `appartment_id` INT NOT NULL,
  `relation_type` ENUM('owner', 'tenant') NOT NULL,
  PRIMARY KEY (`user_email`, `appartment_id`),
  CONSTRAINT `USER_APPARTMENT_FOREIGN_KEY`
    FOREIGN KEY (`user_email`)
    REFERENCES `building_managment`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `APPARTMENT_FOREIGN_KEY`
    FOREIGN KEY (`appartment_id`)
    REFERENCES `building_managment`.`appartment` (`appartment_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
